### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by brandonbloom** [greglook/clj-arrangement#2]
A comment in the code says:

> Sets are compared by cardinality first, then elements in sorted order.

I'm just curious: Why did you choose that strategy? Did you consider any alternatives?

Thanks.

**Comment by greglook** [comment]
I gave this a little bit of thought, but couldn't find a widely-agreed-upon notion of ordering across sets. Comparing on cardinality first was a simple way to ensure that the ordering also preserved (relative) subset ordering; that is, for `A ⊆ B` the set `A` will appear before `B` in the ordered sequence.

Comparing cardinality is also fast, and reduces the amount of element-level comparisons needed, though that was a lower priority consideration.

**Comment by brandonbloom** [comment]
Cool. Both of those points make sense to me.

The main reason I ask is because comparing length first seems precisely wrong for sequences. Clojure does that, but it produces the wrong results for indexing by prefix, which is the most common use case for comparing sequences in my experience.

Part of me wonders if that means it's "wrong" for unordered collections as well. Or if the duality of ordered and unordered means that cardinality-first is precisely right! However, beyond the utility of an arbitrary total order, I'm not sure what value any particular ordering of sets provides, so it's hard to decide which is preferable.

Maybe some category theory fan somewhere has an answer to satisfy my curiosity...

**Comment by greglook** [comment]
> comparing length first seems precisely wrong for sequences... it produces the wrong results for indexing by prefix

Right, which is why I chose to do lexical ordering for sequential collections like lists and vectors. 😁 

> Or if the duality of ordered and unordered means that cardinality-first is precisely right!

That also occurred to me as a nice delineation between the collection types, though this made me go back and check how maps are compared. For consistency, the library should probably have treated maps more like sets (cardinality first, then elements). Instead, they're treated as sequences of entries sorted by key, so `(dec me)` for that one.

**Comment by brandonbloom** [comment]
Thanks for the discussion!
